[sqlservers]
win11 ansible_host=192.168.152.144

[sqlservers:vars]
ansible_user=.\truongtrongphuc
ansible_password='23521225'

ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore

sql_username=scanner_user
sql_password=StrongPassword123!
