---
- name: Remediate CIS Password Policies
  hosts: sqlservers
  gather_facts: no

  vars:
    result_file: "../nt542-db_scanner-gr06/results/password_policies_result.json"

  pre_tasks:

    # =========================
    # LOAD JSON RESULT
    # =========================
    - name: Load password policy scan result JSON
      delegate_to: localhost
      slurp:
        src: "{{ result_file }}"
      register: scan_json_raw

    - name: Parse JSON result
      delegate_to: localhost
      set_fact:
        scan_results: "{{ scan_json_raw.content | b64decode | from_json }}"

    - name: Extract violated rules
      delegate_to: localhost
      set_fact:
        violated_rules: >-
          {{
            scan_results
            | selectattr('status', 'equalto', 'Violate')
            | map(attribute='rule_id')
            | list
          }}

    - name: Show violated rules
      debug:
        var: violated_rules


  tasks:

    # =====================================================
    # RULE 4.3
    # =====================================================
    - name: Remediate Rule 4.3
      win_shell: |
        sqlcmd -S "localhost\SQLEXPRESS" -U "{{ sql_username }}" -P "{{ sql_password }}" -Q "
        DECLARE @sql NVARCHAR(MAX) = '';

        SELECT @sql = @sql + '
        ALTER LOGIN [' + name + '] WITH CHECK_POLICY = ON;'
        FROM sys.sql_logins
        WHERE is_policy_checked = 0;

        EXEC sp_executesql @sql;
        "
      when: "'4.3' in violated_rules"
      register: remediation_4_3

    - name: Show remediation result 4.3
      debug:
        var: remediation_4_3.stdout
      when: "'4.3' in violated_rules"


    # =====================================================
    # RULE 4.2
    # =====================================================
    - name: Remediate Rule 4.2
      win_shell: |
        sqlcmd -S "localhost\SQLEXPRESS" -U "{{ sql_username }}" -P "{{ sql_password }}" -Q "
        DECLARE @sql NVARCHAR(MAX) = '';

        SELECT @sql = @sql + '
        ALTER LOGIN [' + l.name + '] WITH CHECK_EXPIRATION = ON;'
        FROM sys.sql_logins AS l
        WHERE IS_SRVROLEMEMBER('sysadmin', l.name) = 1
        AND l.is_expiration_checked <> 1;

        EXEC sp_executesql @sql;
        "
      when: "'4.2' in violated_rules"
      register: remediation_4_2

    - name: Show remediation result 4.2
      debug:
        var: remediation_4_2.stdout
      when: "'4.2' in violated_rules"
